### ISSUE TITLE
How to update kernel?

### ISSUE THREAD

**Issue by fghsgh** [2bdkid/debian-rpi4-arm64-guide#1]
If one wishes to update the kernel, does it suffice to follow the same steps as for building it for the first time? Will simply overwriting the files on the SD card work? Even if the answer is that simple, this should still be documented.

**Comment by 2bdkid** [comment]
Yes, the steps are essentially the same. You can remove the CROSS_COMPILE flag and adjust /mnt to be /. I would recommend renaming kernel8.img to kernel8.img.old in case the new kernel doesn't boot. Then you can rename the old one back from another computer. Or if you're feeling lucky then just overwrite everything. I'll try to update the guide when I get a moment.

**Comment by 2bdkid** [comment]
I updated the guide with steps in c8deb077d5ef13ee362feef7341a5ce019f59c26
